### ISSUE TITLE
Error with GET with link /auth/callback?code=m1Y1EOw82cnnPX7qexhnFaBcqfeRaB

### ISSUE THREAD

**Issue by makebot-help** [Terminal/ls.terminal.ink#84]
Another error...

---
URL: /auth/callback?code=m1Y1EOw82cnnPX7qexhnFaBcqfeRaB
METHOD: GET

```
InternalOAuthError: Failed to obtain access token
    at Strategy.OAuth2Strategy._createOAuthError (/home/terminal/ls.terminal.ink/node_modules/passport-oauth2/lib/strategy.js:379:17)
    at /home/terminal/ls.terminal.ink/node_modules/passport-oauth2/lib/strategy.js:166:45
    at /home/terminal/ls.terminal.ink/node_modules/oauth/lib/oauth2.js:191:18
    at ClientRequest.<anonymous> (/home/terminal/ls.terminal.ink/node_modules/oauth/lib/oauth2.js:162:5)
    at ClientRequest.emit (events.js:188:13)
    at TLSSocket.socketErrorListener (_http_client.js:399:9)
    at TLSSocket.emit (events.js:188:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
```

**Comment by lepon01** [comment]
I think this is because the token was invalid, did you press the back button by any chance?

**Comment by CircuitCodes** [comment]
Issue seems to be solved, so closing the issue.
